Scalar Operations

In [2]:
import numpy as np

In [7]:
# Scalar Array Multiplication - using * oprator

arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

arr2 = arr1 * arr1
print(arr2)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]


In [6]:
# Exponential Operation - using ** oprator

arr3 = arr1 ** arr1
print(arr3)

[[    1     4    27]
 [  256  3125 46656]]


In [9]:
# # Scalar Subtraction of Array elements

arr4 = arr2-arr1
print(arr4)

[[ 0  2  6]
 [12 20 30]]


In [10]:
# Scalar Division of Array elements

arr5 = 1/arr1
print(arr5)


[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
