Array Indexes

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,100,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [4]:
# Access Indexes of Array

print(arr[0])
print(arr[2])
print(arr[10])

0
4
20


In [5]:
# Silicing of Array - arr[start:stop:step]

print(arr[0:4:1])
print(arr[0:8:2])

[0 2 4 6]
[ 0  4  8 12]


In [6]:
# Updating Array using Slices

arr[0:5] = 0
print(arr)

[ 0  0  0  0  0 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [8]:
# Memory allocation - View vs Copy

arr2 = arr[4:10]
print(arr2)

arr2[:]=1
print(arr2)

[ 0 10 12 14 16 18]
[1 1 1 1 1 1]


In [9]:
# copy() function - creating new memory for array

arr3 = arr.copy()
print(arr3)

[ 0  0  0  0  1  1  1  1  1  1 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
