Array Indexes in Multidimensional Array

In [1]:
import numpy as np

In [2]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# Accessing rows

print(arr2d[0])
print(arr2d[2])

[1 2 3]
[7 8 9]


In [5]:
# Accessing elements of array

print(arr2d[0][0])
print(arr2d[2][2])

1
9


In [7]:
# Slicing in 2D array - arr[start_row:stop_row, start_col:stop_col]

slice1 = arr2d[0:1,0:2]
print(slice1)

[[1 2]]


In [11]:
slice2 = arr2d[0:3,0:1]
print(slice2)

slice3 = arr2d[:3,:1]
print(slice3)

[[1]
 [4]
 [7]]
[[1]
 [4]
 [7]]


In [14]:
# Using loops to change indexs

arr_len = arr2d.shape
print(arr_len)

nrows = arr_len[0]
print(nrows)

(3, 3)
3


In [15]:
for i in range(nrows):
    arr2d[i][0] = 1
    
print(arr2d)

[[1 2 3]
 [1 5 6]
 [1 8 9]]


In [ ]:
# Accessing rows using list of index values

