Premium Array Operations

In [1]:
import numpy as np

In [2]:
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
b = np.arange(5,10)
print(b)

[5 6 7 8 9]


In [5]:
c = np.arange(0,10,2)
print(c)

[0 2 4 6 8]


In [7]:
# Function of Numpy Arrays - sqrt()

d = np.sqrt(c)
print(d)

[0.         1.41421356 2.         2.44948974 2.82842712]


In [8]:
# Function of Numpy Array - exp()

e = np.exp(c)
print(e)

[1.00000000e+00 7.38905610e+00 5.45981500e+01 4.03428793e+02
 2.98095799e+03]


In [12]:
# Function of Numpy Array - random()

f = np.random.randn(5)
print(f)

[-0.1401333  -0.30971705  1.04984724 -1.67781714  0.41043521]


In [11]:
g = np.random.randn(5,5)
print(g)

[[-2.20488806 -0.59225504 -0.87386357  0.10321556 -0.97493428]
 [ 0.88290804  0.98699517 -1.11324386 -0.37246282 -0.74884576]
 [ 0.84404672 -0.46611738 -0.68148602 -0.86794365 -0.39313789]
 [ 1.70009095  1.58509557  0.75786242  0.42654458  0.6899493 ]
 [ 0.55203519  0.42465209  0.36948992  0.89060797  0.02371827]]


In [17]:
# Function of Numpy Array - add()

h = np.add(b,c)
print(h)

[ 5  8 11 14 17]


In [22]:
# Function of Numpy Array - 
# maximum() - finds the maximum among the 2 elements in the array
# minimum() - finds the minimum among the 2 elements in the array
A = np.array([1,5,3,4,5])
B = np.array([6,7,8,3,1])

H = np.maximum(A,B)
print(H)

G = np.minimum(A,B)
print(G)

[6 7 8 4 5]
[1 5 3 3 1]
